language: node_js
sudo: false

node_js:
  - '6.10.2'

branches:
  only:
  - master

install:
  - npm install

script:
  - bash ./scripts/deploy/deploy.sh

before_deploy:
  - gulp clean
  - gulp :build:components:release
  - gulp :build:release:clean-spec
  - cd dist
  - cd ng2v

deploy:
  provider: npm
  skip_cleanup: true
  email: rajkeshwar.pd@gmail.com
  api_key:
    secure: KaiZsmcsfnWuW2PmkoKwb/WCDvguhI+CY4U=
  on:
    branch: master
    repo: rajkeshwar/ng2v
    condition: "/^deploy-.*$/"

cache:
  directories:
    - node_modules
